server:
  port: 9001
spring:
  application:
    name: consumer9001
eureka:
  instance:
    instance-id: consumer
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/