server:
  port: 8041
spring:
  application:
    name: hystrix-provider
eureka:
  instance:
    prefer-ip-address: true # 访问信息有ip信息提示
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"