server:
  port: 8001
spring:
  application:
    name: provider8001
eureka:
  instance:
    instance-id: provider # 主机名称：服务名称修改
    prefer-ip-address: true # 访问信息有ip信息提示
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/