server:
  port: 8031
spring:
  application:
    name: openfeign-provider
eureka:
  instance:
    prefer-ip-address: true # 访问信息有ip信息提示
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/