server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #Seata 事务组名称，对应file.conf文件中 vgroup_mapping.sca-customer-seata-tx-service-group
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: 192.168.1.10:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.10:3306/seata_order
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource


feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
#seata:
#  application-id: ${spring.application.name} # Seata 应用名称，默认使用 ${spring.application.name}
#  tx-service-group: fsp_tx_group # Seata 事务组, 高版本没找到相关配置, 是否可配置未知 选用默认default
#  # 服务配置项
#  service:
#    # 虚拟组和分组的映射 1.0.0以上好像将vgroup-mapping 改为 vgroupMapping, 此处是否影响未测试
#    vgroupMapping:
#      # 此处Key对应 tx-service-group 的 Value, 此处 value 默认 default
#      default: fsp_tx_group
#    # 分组和 Seata 服务的映射 默认端口8091
#    grouplist:
#      default: 127.0.0.1:8091

#seata配置
seata:
  enabled: true
  application-id: ${spring.application.name} # Seata 应用名称，默认使用 ${spring.application.name}
  #这里的名字与file.conf中vgroup_mapping.my_test_tx_group = "default"相同
  tx-service-group: fsp_tx_group
  enable-auto-data-source-proxy: true
  #  use-jdk-proxy: false
  service:
    #这里的名字与file.conf中vgroup_mapping.my_test_tx_group = "default"相同
    vgroup-mapping:
      my_test_tx_group: fsp_tx_group
      #这里的名字与file.conf中default.grouplist = "127.0.0.1:8091"相同
    grouplist:
      default: 127.0.0.1:8091
  #      disable-global-transaction: false
  config:
    type: nacos
    nacos:
      namespace:
      #这里的地址就是你的nacos的地址,可以更换为线上
      serverAddr: 192.168.1.10:8848
      #这里的名字就是registry.conf中 nacos的group名字
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      #这里的地址就是你的nacos的地址,可以更换为线上
      server-addr: 192.168.1.10:8848
      #这里的名字就是registry.conf中 nacos的group名字
      group: SEATA_GROUP
      namespace:
      userName: "nacos"
      password: "nacos"