server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #Seata 事务组名称，对应file.conf文件中 vgroup_mapping.sca-customer-seata-tx-service-group
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: 192.168.1.10:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.10:3306/seata_order
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml

#seata:
#  enabled: true
#  application-id: ${spring.application.name}
#  tx-service-group: my_test_tx_group
#  enable-auto-data-source-proxy: true
#  config:
#    type: nacos
#    nacos:
#      namespace:
#      serverAddr: 192.168.1.10:8848
#      group: SEATA_GROUP
#      userName: "nacos"
#      password: "nacos"
#  registry:
#    type: nacos
#    nacos:
#      application: serverAddr
#      server-addr: 192.168.1.10:8848
#      namespace:
#      userName: "nacos"
#      password: "nacos"