server:
  port: 8400

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
#对Feign的支持
feign:
  sentinel:
    enabled: true
