server:
  port: 9051

spring:
  application:
    name: sleuth-consumer
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率，介于 0 到 1之间，1 表示全部采集
      probability: 1


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/