server:
  port: 9041
spring:
  application:
    name: hystrix-consumer
eureka:
  instance:
    prefer-ip-address: true # 访问信息有ip信息提示
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。
#设置feign客户端超时时间（OpenFeign数以支持ribbon）
ribbon:
  #指的是建立连接所用时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout:  6000
  #指的是建立连接从服务器读取到可用资源所用的时间
  ConnectTimeout: 6000
#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

